/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { forwardRef, useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export const Model = forwardRef((props, ref) => {
  const { nodes } = useGLTF('/paperplane-transformed.glb')
  return (
    <group ref={ref} {...props} dispose={null}>
      <mesh geometry={nodes.Plane.geometry} rotation={[0, -Math.PI * .5, 0]} scale={[2.41, 2.41, 4.3]}>
				{props.children}
			</mesh>
    </group>
  )
});

useGLTF.preload('/paperplane-transformed.glb')

export default Model;
