/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { forwardRef } from "react";
import { useGLTF } from "@react-three/drei";

export const Model = forwardRef((props, ref) => {
  const { nodes, materials } = useGLTF("/spazship-d1-transformed.glb");
  return (
    <group ref={ref} {...props} dispose={null}>
      <mesh geometry={nodes.body.geometry} rotation={[0, Math.PI, 0]} material={materials.body} position={[0, -0.03, 0]}>
        <mesh geometry={nodes.bodyPop.geometry} material={materials.bodyPop} />
        <mesh
          geometry={nodes.boost.geometry}
          material={nodes.boost.material}
          position={[0, 0, -3.28]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.5}
        >
          <mesh geometry={nodes.boostGlow.geometry} material={materials.light} position={[0, 1.43, 0]} />
        </mesh>
        <mesh geometry={nodes.cockpit.geometry} material={materials.cockpit} />
        <mesh geometry={nodes.lights.geometry} material={materials.light} />
        <mesh geometry={nodes.undersidePopArrow.geometry} material={materials.bodyPop} />
        <mesh geometry={nodes.undersidePopRects.geometry} material={materials.bodyPop} />
        <mesh geometry={nodes.wingJoints.geometry} material={materials.bodyHighlight}>
          <mesh geometry={nodes.wingPop.geometry} material={materials.bodyPop} />
          <mesh geometry={nodes.wings.geometry} material={materials.body}>
            <mesh geometry={nodes.wingDecor.geometry} material={materials.light} position={[0, 0.01, 0]} />
          </mesh>
        </mesh>
      </mesh>
    </group>
  );
});

useGLTF.preload("/spazship-d1-transformed.glb");

export default Model;
